name: Short Story Ofthe Day
favicon: null
layout_spectrum: 0.02492
typography_spectrum: 0.6703204
title: Non non-ficton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-35277696-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe292'
    - '#4cf9f7'
    - '#011e2e'
    - '#fe4735'
    - '#f28b4f'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
