name: Short Story Ofthe Day
favicon: null
layout_spectrum: 0.8253
typography_spectrum: 0.6703204
title: 'Non non-fiction  -|-   Accidental quotes  -|-  & Stories with friends, mostly imaginary.'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-35277696-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe292'
    - '#4cf9f7'
    - '#011e2e'
    - '#fe4735'
    - '#f28b4f'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 1
purpose: []
